# Mikefluff/skills Homebrew formula.
#
# To install via tap (recommended):
#   brew tap mikefluff/tap https://github.com/Mikefluff/homebrew-tap
#   brew install mikefluff/tap/skills
#
# Or install directly from this file in the repo:
#   brew install --HEAD https://raw.githubusercontent.com/Mikefluff/skills/main/Formula/skills.rb
#
# After install, run `skills install` to copy the collection into ~/.claude/skills.

class Skills < Formula
  desc "17 Claude Code skills for editing prose, marketing copy, release notes, RFCs, cold email + AI prompts"
  homepage "https://github.com/Mikefluff/skills"
  url "https://github.com/Mikefluff/skills/archive/refs/tags/v1.9.0.tar.gz"
  sha256 "REPLACE_ON_RELEASE"  # Generated by `shasum -a 256 v1.9.0.tar.gz` after each release
  license "MIT"
  head "https://github.com/Mikefluff/skills.git", branch: "main"

  depends_on "python@3.12"
  depends_on "bash"

  def install
    # Install the entire repo into libexec so install.sh + skill folders stay together
    libexec.install Dir["*"]

    # Symlink the CLI shim to bin/
    (bin/"skills").write <<~SH
      #!/usr/bin/env bash
      exec bash "#{libexec}/install.sh" --copy-from "#{libexec}" "$@"
    SH
    chmod 0755, bin/"skills"
  end

  def caveats
    <<~EOS
      Skills are bundled under #{libexec}.
      To copy them into ~/.claude/skills (where Claude Code finds them):

        skills install

      To update later:

        skills update

      To check the standalone writer linter without installing into ~/.claude:

        python3 #{libexec}/writer/scripts/lint.py path/to/draft.md
    EOS
  end

  test do
    # Verify the linter loads
    assert_match "writer-lint", shell_output(
      "echo 'clean prose' | python3 #{libexec}/writer/scripts/lint.py -",
      0
    )
    # Verify the shim is wired
    assert_match "Mikefluff/skills", shell_output("#{bin}/skills --help 2>&1", 0)
  end
end
