#!/usr/bin/env python3
"""
coverage.py — report which of the neuroslop categories defined in
`writer/references/neuroslop-categories.md` are actually detected by regex in
`writer/scripts/lint.py`, and how many patterns each category has.

Usage:
    python3 scripts/coverage.py            # markdown report to stdout
    python3 scripts/coverage.py --json     # machine-readable JSON
    python3 scripts/coverage.py --write    # write docs/LINTER-COVERAGE.md
    python3 scripts/coverage.py --check    # exit 1 if that file is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CAT_FILE = ROOT / "writer" / "references" / "neuroslop-categories.md"
LINT_FILE = ROOT / "writer" / "scripts" / "lint.py"


def parse_categories(text: str) -> list[dict]:
    """Extract the 23 numbered category headers from neuroslop-categories.md."""
    out: list[dict] = []
    pat = re.compile(r"^## (\d+)\. ([A-Z_]+)\b\s*(?:—|--)?\s*(.*)$")
    for line in text.splitlines():
        m = pat.match(line)
        if m:
            out.append({
                "number": int(m.group(1)),
                "name": m.group(2),
                "blurb": m.group(3).strip(),
            })
    return out


def parse_patterns(text: str) -> dict[str, int]:
    """Count regex patterns per category in lint.py PATTERNS list."""
    counts: dict[str, int] = {}
    pat = re.compile(r'\(\s*"([A-Z_]+)"\s*,\s*r')
    for m in pat.finditer(text):
        cat = m.group(1)
        counts[cat] = counts.get(cat, 0) + 1
    return counts


def status_for(count: int) -> tuple[str, str]:
    if count >= 3:
        return ("covered", "✓")
    if count >= 1:
        return ("partial", "⚠")
    return ("missing", "✗")


# Notes about why specific categories are intentionally LLM-only.
LLM_ONLY_NOTES = {
    "INFLATED_TRIPLET": "requires semantic check on three abstract nouns; regex too brittle.",
    "FALSE_RANGE": "no regex on purpose — legitimate ranges (\"от 5 до 10\", \"от Москвы до Владивостока\") vastly outnumber the slop form, so this one is checked by eye.",
    "BALANCE_HEDGE": "AI-fingerprint detection at paragraph level, not line level — regex misses cadence.",
    "TYPOGRAPHY": "regex catches straight + curly quotes; numbers-as-words stays LLM territory. The em-dash is no longer here — it is a hard ban (EM_DASH_RU), gated to Cyrillic lines and demoted to a nit under --fiction.",
    "SUPERLATIVE_OVERLOAD": "partial by design — Russian morphology makes \"самый X-ный\" hard to scope, so only the narrow EN forms and a couple of RU ones are matched.",
    "SELFHELP": "low base rate in author's corpus; LLM picks up rare hits well enough.",
}


def render_markdown(report: dict) -> str:
    lines: list[str] = []
    lines.append("# Linter coverage — writer/scripts/lint.py")
    lines.append("")
    lines.append("> Auto-generated by `make coverage` / `python3 scripts/coverage.py`.")
    lines.append("> Compares categories from `writer/references/neuroslop-categories.md`")
    lines.append("> against regex patterns in `writer/scripts/lint.py`.")
    lines.append("")
    lines.append("| # | Category | Status | Patterns |")
    lines.append("|---|---|---|---|")
    for cat in report["categories"]:
        symbol = "✓" if cat["status"] == "covered" else ("⚠" if cat["status"] == "partial" else "✗")
        lines.append(f"| {cat['number']} | `{cat['name']}` | {symbol} {cat['status']} | {cat['patterns']} |")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total categories: **{report['total']}**")
    lines.append(f"- Covered (≥ 3 patterns): **{report['covered']}**")
    lines.append(f"- Partial (1-2 patterns): **{report['partial']}**")
    lines.append(f"- Missing (0 patterns): **{report['missing']}**")
    lines.append("")

    notes = [c for c in report["categories"] if c["name"] in LLM_ONLY_NOTES]
    if notes:
        lines.append("## Why some categories are intentionally LLM-only")
        lines.append("")
        for c in notes:
            note = LLM_ONLY_NOTES.get(c["name"], "")
            lines.append(f"- **`{c['name']}`** — {note}")
        lines.append("")

    lines.append("## Reading this")
    lines.append("")
    lines.append("- `covered` = the offline `lint.py` reliably catches this category.")
    lines.append("- `partial` = some pattern coverage, but expect to miss variants — LLM cleaning pass is the safety net.")
    lines.append("- `missing` = either intentionally LLM-only (see notes above), or a real gap to fix in `lint.py`.")
    lines.append("")
    lines.append("## Not in this table")
    lines.append("")
    lines.append("This table covers the *probabilistic* catalogue only — the categories that")
    lines.append("mean something in clusters. Two other detector families run alongside it and")
    lines.append("are not scored here because coverage is not the right question for them:")
    lines.append("")
    lines.append("- **Hard bans** (`EM_DASH_RU`, `MATH_SIGN_PROSE`, `NEG_PARALLEL`, `CHOPPED_DRAMA`,")
    lines.append("  `COPYPASTE_ARTIFACT`) — pass/fail, not density. One hit fails the gate.")
    lines.append("- **Structural detectors** (`RHYTHM_MONOTONE`, `RHYTHM_NO_SHORT`, `VERB_ECHO`,")
    lines.append("  `BOLD_DENSITY`, `HEADING_ECHO`, `HEDGE_CASCADE`, `COLON_REVEAL`) — computed")
    lines.append("  over the whole document rather than matched per line, so they have no")
    lines.append("  pattern count to report.")
    lines.append("")
    # Single trailing newline (markdownlint MD012 catches multiple)
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--json", action="store_true", help="emit JSON instead of markdown")
    p.add_argument("--write", action="store_true",
                   help="write docs/LINTER-COVERAGE.md instead of printing")
    p.add_argument("--check", action="store_true",
                   help="exit 1 if docs/LINTER-COVERAGE.md is stale")
    args = p.parse_args(argv)

    if not CAT_FILE.exists():
        print(f"missing {CAT_FILE}", file=sys.stderr)
        return 2
    if not LINT_FILE.exists():
        print(f"missing {LINT_FILE}", file=sys.stderr)
        return 2

    cats = parse_categories(CAT_FILE.read_text(encoding="utf-8"))
    patterns = parse_patterns(LINT_FILE.read_text(encoding="utf-8"))

    rows: list[dict] = []
    covered = partial = missing = 0
    for cat in cats:
        n = patterns.get(cat["name"], 0)
        status, _ = status_for(n)
        if status == "covered":
            covered += 1
        elif status == "partial":
            partial += 1
        else:
            missing += 1
        rows.append({
            "number": cat["number"],
            "name": cat["name"],
            "status": status,
            "patterns": n,
        })

    # Sort by number to match the catalogue
    rows.sort(key=lambda r: r["number"])

    report = {
        "total": len(cats),
        "covered": covered,
        "partial": partial,
        "missing": missing,
        "categories": rows,
    }

    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
        return 0

    md = render_markdown(report)
    target = ROOT / "docs" / "LINTER-COVERAGE.md"
    if args.write:
        target.write_text(md, encoding="utf-8")
        print(f"Updated {target.relative_to(ROOT)}")
        return 0
    if args.check:
        # The doc is generated from the catalogue and the linter. It went stale
        # once already — new categories shipped and nothing compared the two.
        if not target.is_file():
            print(f"coverage: FAILED — {target.relative_to(ROOT)} does not exist")
            return 1
        if target.read_text(encoding="utf-8") != md:
            print("coverage: FAILED — LINTER-COVERAGE.md is out of date")
            print("  run: python3 scripts/coverage.py --write")
            return 1
        print("coverage: OK (LINTER-COVERAGE.md matches the catalogue + linter)")
        return 0
    print(md, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
