#!/usr/bin/env python3
"""
coverage.py — report which of the neuroslop categories defined in
`writer/references/neuroslop-categories.md` are actually detected by regex in
`writer/scripts/lint_patterns.py`, and how many patterns each category has.

Usage:
    python3 scripts/coverage.py            # markdown report to stdout
    python3 scripts/coverage.py --json     # machine-readable JSON
    python3 scripts/coverage.py --write    # write docs/LINTER-COVERAGE.md
    python3 scripts/coverage.py --check    # exit 1 if that file is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CAT_FILE = ROOT / "writer" / "references" / "neuroslop-categories.md"
LINT_FILE = ROOT / "writer" / "scripts" / "lint_patterns.py"

STATUS_SYMBOL = {"covered": "✓", "partial": "⚠", "missing": "✗"}


def parse_categories(text: str) -> list[dict]:
    """Extract the 23 numbered category headers from neuroslop-categories.md."""
    out: list[dict] = []
    pat = re.compile(r"^## (\d+)\. ([A-Z_]+)\b\s*(?:—|--)?\s*(.*)$")
    for line in text.splitlines():
        m = pat.match(line)
        if m:
            out.append({
                "number": int(m.group(1)),
                "name": m.group(2),
                "blurb": m.group(3).strip(),
            })
    return out


def parse_patterns(text: str) -> dict[str, int]:
    """Count regex patterns per category in the PATTERNS catalogue."""
    counts: dict[str, int] = {}
    pat = re.compile(r'\(\s*"([A-Z_]+)"\s*,\s*r')
    for m in pat.finditer(text):
        cat = m.group(1)
        counts[cat] = counts.get(cat, 0) + 1
    return counts


def status_for(count: int) -> tuple[str, str]:
    if count >= 3:
        return ("covered", STATUS_SYMBOL["covered"])
    if count >= 1:
        return ("partial", STATUS_SYMBOL["partial"])
    return ("missing", STATUS_SYMBOL["missing"])


# Notes about why specific categories are intentionally LLM-only.
LLM_ONLY_NOTES = {
    "INFLATED_TRIPLET": "requires semantic check on three abstract nouns; regex too brittle.",
    "FALSE_RANGE": "no regex on purpose — legitimate ranges (\"от 5 до 10\", \"от Москвы до Владивостока\") vastly outnumber the slop form, so this one is checked by eye.",
    "BALANCE_HEDGE": "AI-fingerprint detection at paragraph level, not line level — regex misses cadence.",
    "TYPOGRAPHY": "regex catches straight + curly quotes; numbers-as-words stays LLM territory. The em-dash is no longer here — it is a hard ban (EM_DASH_RU), gated to Cyrillic lines and demoted to a nit under --fiction.",
    "SUPERLATIVE_OVERLOAD": "partial by design — Russian morphology makes \"самый X-ный\" hard to scope, so only the narrow EN forms and a couple of RU ones are matched.",
    "SELFHELP": "low base rate in author's corpus; LLM picks up rare hits well enough.",
}

# The prose around the table never varies, so it lives here rather than as forty
# consecutive append() calls that hide the two lines which do vary.
_INTRO = """\
# Linter coverage — writer/scripts/lint.py

> Auto-generated by `make coverage` / `python3 scripts/coverage.py`.
> Compares categories from `writer/references/neuroslop-categories.md`
> against regex patterns in `writer/scripts/lint_patterns.py`.

| # | Category | Status | Patterns |
|---|---|---|---|"""

_OUTRO = """\
## Reading this

- `covered` = the offline `lint.py` reliably catches this category.
- `partial` = some pattern coverage, but expect to miss variants — LLM cleaning pass is the safety net.
- `missing` = either intentionally LLM-only (see notes above), or a real gap to fix in the catalogue.

## Not in this table

This table covers the *probabilistic* catalogue only — the categories that
mean something in clusters. Two other detector families run alongside it and
are not scored here because coverage is not the right question for them:

- **Hard bans** (`EM_DASH_RU`, `MATH_SIGN_PROSE`, `NEG_PARALLEL`, `CHOPPED_DRAMA`,
  `COPYPASTE_ARTIFACT`) — pass/fail, not density. One hit fails the gate.
- **Structural detectors** (`RHYTHM_MONOTONE`, `RHYTHM_NO_SHORT`, `VERB_ECHO`,
  `BOLD_DENSITY`, `HEADING_ECHO`, `HEDGE_CASCADE`, `COLON_REVEAL`) — computed
  over the whole document rather than matched per line, so they have no
  pattern count to report."""


def render_markdown(report: dict) -> str:
    lines = _INTRO.splitlines()
    lines += [
        f"| {c['number']} | `{c['name']}` | {STATUS_SYMBOL[c['status']]} {c['status']} "
        f"| {c['patterns']} |"
        for c in report["categories"]
    ]
    lines += [
        "",
        "## Summary",
        "",
        f"- Total categories: **{report['total']}**",
        f"- Covered (≥ 3 patterns): **{report['covered']}**",
        f"- Partial (1-2 patterns): **{report['partial']}**",
        f"- Missing (0 patterns): **{report['missing']}**",
        "",
    ]

    noted = [c for c in report["categories"] if c["name"] in LLM_ONLY_NOTES]
    if noted:
        lines += ["## Why some categories are intentionally LLM-only", ""]
        lines += [f"- **`{c['name']}`** — {LLM_ONLY_NOTES[c['name']]}" for c in noted]
        lines += [""]

    lines += _OUTRO.splitlines()
    # Single trailing newline (markdownlint MD012 catches multiple)
    return "\n".join(lines).rstrip("\n") + "\n"


def build_report(cats: list[dict], patterns: dict[str, int]) -> dict:
    """Score every catalogue category by how many regexes the catalogue has for it."""
    rows: list[dict] = []
    tally = {"covered": 0, "partial": 0, "missing": 0}
    for cat in cats:
        n = patterns.get(cat["name"], 0)
        status, _ = status_for(n)
        tally[status] += 1
        rows.append({
            "number": cat["number"],
            "name": cat["name"],
            "status": status,
            "patterns": n,
        })
    rows.sort(key=lambda r: r["number"])  # match the catalogue's own order
    return {"total": len(cats), **tally, "categories": rows}


def check_up_to_date(target: Path, rendered: str) -> int:
    """The doc is generated from the catalogue and the linter. It went stale
    once already — new categories shipped and nothing compared the two."""
    if not target.is_file():
        print(f"coverage: FAILED — {target.relative_to(ROOT)} does not exist")
        return 1
    if target.read_text(encoding="utf-8") != rendered:
        print("coverage: FAILED — LINTER-COVERAGE.md is out of date")
        print("  run: python3 scripts/coverage.py --write")
        return 1
    print("coverage: OK (LINTER-COVERAGE.md matches the catalogue + linter)")
    return 0


def emit(report: dict, args: argparse.Namespace) -> int:
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
        return 0

    rendered = render_markdown(report)
    target = ROOT / "docs" / "LINTER-COVERAGE.md"
    if args.write:
        target.write_text(rendered, encoding="utf-8")
        print(f"Updated {target.relative_to(ROOT)}")
        return 0
    if args.check:
        return check_up_to_date(target, rendered)
    print(rendered, end="")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--json", action="store_true", help="emit JSON instead of markdown")
    p.add_argument("--write", action="store_true",
                   help="write docs/LINTER-COVERAGE.md instead of printing")
    p.add_argument("--check", action="store_true",
                   help="exit 1 if docs/LINTER-COVERAGE.md is stale")
    args = p.parse_args(argv)

    for required in (CAT_FILE, LINT_FILE):
        if not required.exists():
            print(f"missing {required}", file=sys.stderr)
            return 2

    report = build_report(
        parse_categories(CAT_FILE.read_text(encoding="utf-8")),
        parse_patterns(LINT_FILE.read_text(encoding="utf-8")),
    )
    return emit(report, args)


if __name__ == "__main__":
    sys.exit(main())
