#!/usr/bin/env python3
"""Generate common/references/model-pricing.md from cost.PRICE_TABLE.

Prices were previously written by hand into ten separate `model-picker.md` files.
They happened to agree today, but nothing enforced that, and nothing tied any of
them to `common/runners/cost.py` — the table that actually estimates the bill and
decides whether to prompt for confirmation. A doc that disagrees with the code is
worse than no doc: it is a number the reader trusts.

So the doc is generated from the code, and `--check` fails CI if it drifts.

Usage:
    python3 scripts/gen-pricing.py            # print to stdout
    python3 scripts/gen-pricing.py --write    # write the file
    python3 scripts/gen-pricing.py --check    # exit 1 if the file is stale
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from common.runners.cost import (  # noqa: E402
    CONFIRMATION_THRESHOLD,
    PRICE_TABLE,
    _BUDGET_ENV_OVERRIDE,
    _DEFAULT_BUDGETS,
)

TARGET = ROOT / "common" / "references" / "model-pricing.md"

UNIT_LABEL = {
    "per_image": "per image",
    "per_edit": "per edit",
    "per_song": "per song",
    "per_second": "per second",
    "per_minute": "per minute",
    "per_1k_chars": "per 1 000 characters",
    "low": "quality: low",
    "medium": "quality: medium",
    "high": "quality: high",
}

VENDOR_ORDER = [
    ("OpenAI", ("gpt-image-2", "gpt-4o-mini-tts", "whisper-1", "sora-2", "sora-2-pro")),
    ("Google", ("imagen-4", "imagen-4-ultra", "imagen-4-fast", "nano-banana-pro",
                "veo-3-1", "veo-3-1-fast", "lyria-3-pro")),
    ("Black Forest Labs", ("flux-1-1-pro", "flux-2-pro", "flux-kontext", "flux-schnell")),
    ("Ideogram", ("ideogram-3-turbo", "ideogram-3", "ideogram-3-quality")),
    ("Runway", ("gen-4", "gen-4-turbo", "aleph")),
    ("Kling", ("kling-3",)),
    ("Suno", ("suno-v5-5",)),
    ("ElevenLabs", ("eleven-music", "eleven-tts")),
    ("Aggregators (median estimate)", ("fal/any", "replicate/any")),
]


def render() -> str:
    out: list[str] = []
    add = out.append

    add("<!-- GENERATED by scripts/gen-pricing.py — do not edit by hand. -->")
    add("<!-- Source of truth: common/runners/cost.py PRICE_TABLE. -->")
    add("")
    add("# Model pricing")
    add("")
    add("Generated from `common/runners/cost.py`, the same table that estimates cost")
    add("before a run and decides whether to ask for confirmation. Editing this file")
    add("changes nothing — edit `PRICE_TABLE` and regenerate.")
    add("")
    add("Figures are conservative per-unit USD, snapshotted from vendor pricing pages.")
    add("Actual cost may come in slightly lower; it should never come in higher. Batch")
    add("totals quoted elsewhere in the skills are these numbers multiplied by the item")
    add("count, not separate prices.")
    add("")

    seen: set[str] = set()
    for vendor, models in VENDOR_ORDER:
        rows = [(m, PRICE_TABLE[m]) for m in models if m in PRICE_TABLE]
        if not rows:
            continue
        add(f"## {vendor}")
        add("")
        add("| Model | Unit | USD |")
        add("|---|---|---|")
        for name, entry in rows:
            seen.add(name)
            for unit, price in entry.items():
                add(f"| `{name}` | {UNIT_LABEL.get(unit, unit)} | ${price} |")
        add("")

    leftover = sorted(set(PRICE_TABLE) - seen)
    if leftover:
        add("## Other")
        add("")
        add("| Model | Unit | USD |")
        add("|---|---|---|")
        for name in leftover:
            for unit, price in PRICE_TABLE[name].items():
                add(f"| `{name}` | {UNIT_LABEL.get(unit, unit)} | ${price} |")
        add("")

    add("## Confirmation thresholds")
    add("")
    add(f"A single call estimated above **${CONFIRMATION_THRESHOLD}** prompts before running.")
    add("Pass `--yes` to skip the prompt. An unknown model estimates as `None`, which")
    add("never prompts — unknown is not the same as free, so check the vendor's page.")
    add("")
    add("Batch runs ask once for the aggregate instead of once per item, and warn when")
    add("the total exceeds the per-modality budget:")
    add("")
    add("| Modality | Default budget | Env override |")
    add("|---|---|---|")
    for modality, budget in _DEFAULT_BUDGETS.items():
        add(f"| {modality} | ${budget} | `{_BUDGET_ENV_OVERRIDE[modality]}` |")
    add("")
    return "\n".join(out) + "\n"


def main() -> int:
    content = render()
    if "--write" in sys.argv:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(content, encoding="utf-8")
        print(f"Updated {TARGET.relative_to(ROOT)}")
        return 0
    if "--check" in sys.argv:
        if not TARGET.is_file():
            print(f"pricing: FAILED — {TARGET.relative_to(ROOT)} does not exist")
            return 1
        if TARGET.read_text(encoding="utf-8") != content:
            print("pricing: FAILED — model-pricing.md is out of date with cost.PRICE_TABLE")
            print("  run: python3 scripts/gen-pricing.py --write")
            return 1
        print("pricing: OK (model-pricing.md matches cost.PRICE_TABLE)")
        return 0
    sys.stdout.write(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
